services:
  - type: web
    name: bank
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bank.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: bank.settings
      - key: SECRET_KEY
        value: django-insecure-46q_46a3%f4x$s)$vjh(te@=q(xdp$q0jq2k&k)5(pr_4id5-(
      - key: DEBUG
        value: "True"
